Add golang.org/x/sys to WORKSPACE
The result of:
bazel run //:gazelle -- update-repos golang.org/x/sys

This resolved an error of the form:
$ bazel build //...
[...snip...]
ERROR: /home/chromy/.cache/bazel/_bazel_chromy/ca4a0af3e2282fdc79af362ae706ecf4/external/org_golang_google_grpc/internal/syscall/BUILD.bazel:3:11: GoCompilePkg external/org_golang_google_grpc/internal/syscall/syscall.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/org_golang_google_grpc/internal/syscall/syscall_linux.go -src ... (remaining 23 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
        /home/chromy/.cache/bazel/_bazel_chromy/ca4a0af3e2282fdc79af362ae706ecf4/sandbox/linux-sandbox/3544/execroot/com_github_livegrep_livegrep/external/org_golang_google_grpc/internal/syscall/syscall_linux.go: import of "golang.org/x/sys/unix"
No dependencies were provided.

On the platform:
$ uname -a
Linux astra 6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux
$ bazel --version
bazel 5.3.2

The command was suggested by:
https://stackoverflow.com/a/77743203/695467
but I don't understand go/bazel enough to know what that means.